### ISSUE TITLE
Kurzweil K2000R does not boot...

### ISSUE THREAD

**Issue by romeczek73** [erichelgeson/BlueSCSI#273] opened 2024-08-24 06:41 UTC
My Kurzweil K2000R does not boot with BlueSCSI v2 connected. Tested with termination on and off. Please help...

[log.txt](https://github.com/user-attachments/files/16735580/log.txt)

**Comment by erichelgeson** [comment] 2024-08-25 14:17
This repo is for BlueSCSI v1 - and is a duplicate of https://github.com/BlueSCSI/BlueSCSI-v2/discussions/177

**Closed as completed by erichelgeson** 2024-08-25 14:17 UTC
